name: sentinel-5p
channels:
  - conda-forge
  - defaults
  - esri
  - stcorp
dependencies:
  - affine=2.3.0=py_0
  - alembic=1.4.2=pyh9f0ad1d_0
  - appdirs=1.4.3=py_1
  - attrs=19.3.0=py_0
  - autopep8=1.5.3=pyh9f0ad1d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - black=19.10b0=py37_0
  - blas=1.0=mkl
  - bleach=3.1.5=pyh9f0ad1d_0
  - boost-cpp=1.72.0=h0caebb8_0
  - brotlipy=0.7.0=py37h4ab8f01_1000
  - bzip2=1.0.8=hfa6e2cd_2
  - ca-certificates=2020.6.20=hecda079_0
  - certifi=2020.6.20=py37hc8dfbb8_0
  - cffi=1.14.0=py37ha419a9e_0
  - cfgv=3.2.0=py_0
  - cfitsio=3.470=he774522_5
  - chardet=3.0.4=py37hc8dfbb8_1006
  - click=7.1.2=pyh9f0ad1d_0
  - click-plugins=1.1.1=py_0
  - cligj=0.5.0=py_0
  - cloudpickle=1.4.1=py_0
  - coda=2.21.1=py37h39e3cac_0
  - colorama=0.4.3=py_0
  - cryptography=2.9.2=py37h26f1ce3_0
  - curl=7.68.0=h4496350_0
  - cycler=0.10.0=py_2
  - cytoolz=0.10.1=py37hfa6e2cd_0
  - dask-core=2.19.0=py_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - distlib=0.3.1=pyh9f0ad1d_0
  - earthpy=0.9.2=py_0
  - editdistance=0.5.3=py37h1834ac0_1
  - entrypoints=0.3=py37hc8dfbb8_1001
  - expat=2.2.9=he025d50_2
  - filelock=3.0.12=pyh9f0ad1d_0
  - fiona=1.8.13=py37hb7fdc2d_0
  - freetype=2.9.1=vc14_0
  - freexl=1.0.5=hd288d7e_1002
  - fuzzywuzzy=0.17.0=py_0
  - gdal=3.0.2=py37hdf43c64_0
  - geopandas=0.8.0=py_1
  - geos=3.8.0=he025d50_1
  - geotiff=1.5.1=h765a46f_7
  - harp=1.11=py37h39e3cac_0
  - hdf4=4.2.13=hf8e6fe8_1003
  - hdf5=1.10.4=nompi_hcc15c50_1106
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha925a31_3
  - identify=1.5.2=pyh9f0ad1d_0
  - idna=2.10=pyh9f0ad1d_0
  - imagecodecs-lite=2019.12.3=py37h44b1f71_1
  - imageio=2.8.0=py_0
  - importlib-metadata=1.7.0=py37hc8dfbb8_0
  - importlib_metadata=1.7.0=0
  - intel-openmp=2019.4=245
  - ipykernel=5.3.0=py37h5ca1d4c_0
  - ipython=7.16.1=py37h43977f1_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.5.1=py_0
  - jedi=0.17.1=py37hc8dfbb8_0
  - jinja2=2.11.2=pyh9f0ad1d_0
  - jpeg=9d=he774522_0
  - json5=0.9.4=pyh9f0ad1d_0
  - jsonschema=3.2.0=py37hc8dfbb8_1
  - jupyter=1.0.0=py_2
  - jupyter_client=6.1.3=py_0
  - jupyter_console=6.1.0=py_1
  - jupyter_contrib_core=0.3.3=py_2
  - jupyter_contrib_nbextensions=0.5.1=py37_0
  - jupyter_core=4.6.3=py37hc8dfbb8_1
  - jupyter_highlight_selected_word=0.2.0=py37_1000
  - jupyter_latex_envs=1.4.4=py37_1000
  - jupyter_nbextensions_configurator=0.4.1=py37_0
  - jupyterlab=2.1.5=py_0
  - jupyterlab_server=1.1.5=py_0
  - kealib=1.4.7=h07cbb95_6
  - kiwisolver=1.2.0=py37heaa310e_0
  - krb5=1.16.4=hdd46e55_0
  - libblas=3.8.0=14_mkl
  - libcblas=3.8.0=14_mkl
  - libcurl=7.68.0=h4496350_0
  - libgdal=3.0.2=h1155b67_0
  - libiconv=1.15=hfa6e2cd_1006
  - libkml=1.3.0=h7e985d0_1011
  - liblapack=3.8.0=14_mkl
  - libnetcdf=4.6.2=h396784b_1001
  - libpng=1.6.37=hfe6a214_1
  - libpq=11.5=hb0bdaea_2
  - libsodium=1.0.17=h2fa13f4_0
  - libspatialindex=1.9.3=he025d50_3
  - libspatialite=4.3.0a=he9c6e69_1033
  - libssh2=1.9.0=h3235a2c_2
  - libtiff=4.1.0=h56a325e_0
  - libxml2=2.9.10=h5d81f1c_1
  - libxslt=1.1.33=h579f668_1
  - lxml=4.5.1=py37h8ba8a40_0
  - lz4=3.0.2=py37h088f9ae_1
  - lz4-c=1.8.3=he025d50_1001
  - m2w64-expat=2.1.1=2
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gettext=0.19.7=2
  - m2w64-gmp=6.1.0=2
  - m2w64-libiconv=1.14=6
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - m2w64-xz=5.2.2=2
  - mako=1.1.0=py_0
  - markupsafe=1.1.1=py37h8055547_1
  - matplotlib=3.2.1=0
  - matplotlib-base=3.2.1=py37h911224e_0
  - mistune=0.8.4=py37h8055547_1001
  - mkl=2019.4=245
  - mkl-service=2.3.0=py37hfa6e2cd_0
  - msys2-conda-epoch=20160418=1
  - munch=2.5.0=py_0
  - mypy_extensions=0.4.3=py37hc8dfbb8_1
  - nbclean=0.3.2=pyh5ca1d4c_0
  - nbconvert=5.6.1=py37hc8dfbb8_1
  - nbformat=5.0.6=py_0
  - nbgrader=0.6.1=py37hc8dfbb8_0
  - networkx=2.4=py_1
  - nodeenv=1.5.0=pyh9f0ad1d_0
  - notebook=6.0.3=py37hc8dfbb8_0
  - numpy=1.18.5=py37hae9e721_0
  - olefile=0.46=py_0
  - openjpeg=2.3.1=h57dd2e7_3
  - openssl=1.1.1g=he774522_1
  - packaging=20.4=pyh9f0ad1d_0
  - pandas=1.0.5=py37h3bbf574_0
  - pandoc=2.9.2.1=0
  - pandocfilters=1.4.2=py_1
  - parso=0.7.0=pyh9f0ad1d_0
  - pathspec=0.8.0=pyh9f0ad1d_0
  - patsy=0.5.1=py_0
  - pcre=8.44=h6538335_0
  - pickleshare=0.7.5=py37hc8dfbb8_1001
  - pillow=7.1.2=py37hc826c6e_0
  - pip=20.1.1=py_1
  - postgresql=11.5=h06f7779_2
  - pre-commit=2.7.1=py37hc8dfbb8_0
  - proj=6.2.1=ha7a8c7b_0
  - prometheus_client=0.8.0=pyh9f0ad1d_0
  - prompt-toolkit=3.0.5=py_1
  - prompt_toolkit=3.0.5=1
  - pycodestyle=2.6.0=pyh9f0ad1d_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.6.1=py_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyproj=2.4.2.post1=py37h9716dcf_0
  - pyqt=5.9.2=py37h6538335_4
  - pyrsistent=0.16.0=py37h8055547_0
  - pysocks=1.7.1=py37hc8dfbb8_1
  - python=3.7.6=cpython_h60c2a47_6
  - python-dateutil=2.8.1=py_0
  - python-editor=1.0.4=py_0
  - python-levenshtein=0.12.0=py37h8055547_1002
  - python_abi=3.7=1_cp37m
  - pytz=2020.1=pyh9f0ad1d_0
  - pywavelets=1.1.1=py37h44b1f71_1
  - pywin32=227=py37hfa6e2cd_0
  - pywinpty=0.5.7=py37_0
  - pyyaml=5.3.1=py37h8055547_0
  - pyzmq=19.0.1=py37h453f00a_0
  - qt=5.9.7=hc6833c9_1
  - qtconsole=4.7.5=pyh9f0ad1d_0
  - qtpy=1.9.0=py_0
  - rasterio=1.1.2=py37h2617b1b_0
  - regex=2020.6.8=py37h4ab8f01_0
  - requests=2.24.0=pyh9f0ad1d_0
  - rtree=0.9.4=py37h804a536_1
  - scikit-image=0.17.2=py37h3bbf574_1
  - scipy=1.3.1=py37h29ff71c_0
  - seaborn=0.10.1=1
  - seaborn-base=0.10.1=py_1
  - send2trash=1.5.0=py_0
  - setuptools=47.3.1=py37hc8dfbb8_0
  - shapely=1.7.0=py37h13a63d7_1
  - sip=4.19.8=py37h6538335_1000
  - six=1.15.0=pyh9f0ad1d_0
  - snuggs=1.4.7=py_0
  - sqlalchemy=1.3.18=py37h4ab8f01_0
  - sqlite=3.32.3=he774522_0
  - statsmodels=0.11.1=py37h4ab8f01_2
  - tbb=2018.0.5=he980bc4_0
  - terminado=0.8.3=py37hc8dfbb8_1
  - testpath=0.4.4=py_0
  - tifffile=2020.6.3=py_0
  - tiledb=1.6.3=h7b000aa_0
  - tk=8.6.10=hfa6e2cd_0
  - toml=0.10.1=pyh9f0ad1d_0
  - toolz=0.10.0=py_0
  - tornado=6.0.4=py37hfa6e2cd_0
  - tqdm=4.47.0=pyh9f0ad1d_0
  - traitlets=4.3.3=py37hc8dfbb8_1
  - typed-ast=1.4.1=py37hfa6e2cd_0
  - typing_extensions=3.7.4.2=py_0
  - urllib3=1.25.9=py_0
  - vc=14.1=h869be7e_1
  - virtualenv=20.0.20=py37hc8dfbb8_1
  - vs2015_runtime=14.16.27012=h30e32a0_2
  - wcwidth=0.2.5=pyh9f0ad1d_0
  - webencodings=0.5.1=py_1
  - wheel=0.34.2=py_1
  - widgetsnbextension=3.5.1=py37_0
  - win_inet_pton=1.1.0=py37_0
  - wincertstore=0.2=py37_1003
  - winpty=0.4.3=4
  - xerces-c=3.2.3=ha925a31_1
  - xz=5.2.5=h2fa13f4_0
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.2=h6538335_2
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h2fa13f4_1006
  - zstd=1.3.7=haafe652_1001
  - pip:
    - boxsdk==2.9.0
    - cftime==1.1.3
    - netcdf4==1.5.3
    - requests-toolbelt==0.9.1
    - wrapt==1.12.1
